// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SST.StockImport.Infrastructure.Data;

#nullable disable

namespace SST.StockImport.Infrastructure.Migrations
{
    [DbContext(typeof(StockImportDbContext))]
    [Migration("20251129033149_InitialMigrationAlignedToLegacy")]
    partial class InitialMigrationAlignedToLegacy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SST.StockImport.Core.Entities.AlertLog", b =>
                {
                    b.Property<long>("Log_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Log_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Log_ID"));

                    b.Property<string>("AlertTitle")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("AlertTitle");

                    b.Property<string>("AlertType")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("AlertType");

                    b.Property<int?>("Avg5Vol")
                        .HasColumnType("int")
                        .HasColumnName("avg5Vol");

                    b.Property<decimal?>("Avg5VolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avg5VolRate");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("CREATED");

                    b.Property<decimal?>("CurrPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CurrPrice");

                    b.Property<int?>("CurrVol")
                        .HasColumnType("int")
                        .HasColumnName("CurrVol");

                    b.Property<decimal?>("DiffPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("diffPrice");

                    b.Property<decimal?>("DiffRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("DiffRate");

                    b.Property<string>("InstRiseFallRate")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("InstRiseFallRate");

                    b.Property<int?>("InstantBuyVol")
                        .HasColumnType("int")
                        .HasColumnName("instantBuyVol");

                    b.Property<int?>("InstantFall")
                        .HasColumnType("int")
                        .HasColumnName("instantFall");

                    b.Property<string>("InstantIdx")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("instantIdx");

                    b.Property<int?>("InstantJumpKong")
                        .HasColumnType("int")
                        .HasColumnName("instantJumpKong");

                    b.Property<int?>("InstantMass")
                        .HasColumnType("int")
                        .HasColumnName("instantMass");

                    b.Property<int?>("InstantRise")
                        .HasColumnType("int")
                        .HasColumnName("instantRise");

                    b.Property<int?>("InstantSellVol")
                        .HasColumnType("int")
                        .HasColumnName("instantSellVol");

                    b.Property<decimal?>("LastPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("lastPrice");

                    b.Property<int?>("LastVol")
                        .HasColumnType("int")
                        .HasColumnName("lastVol");

                    b.Property<decimal?>("LastVolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("lastVolRate");

                    b.Property<int?>("MessFall")
                        .HasColumnType("int")
                        .HasColumnName("messFall");

                    b.Property<int?>("MessRise")
                        .HasColumnType("int")
                        .HasColumnName("messRise");

                    b.Property<decimal?>("OpenPriec")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("OpenPriec");

                    b.Property<decimal?>("PanAmtDiff")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("panAmtDiff");

                    b.Property<decimal?>("PanAmtRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("panAmtRate");

                    b.Property<decimal?>("PanAvg5VolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("panAvg5VolRate");

                    b.Property<decimal?>("PanAvgVolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("panAvgVolRate");

                    b.Property<decimal?>("PanLastVolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("panLastVolRate");

                    b.Property<int?>("PanTrans")
                        .HasColumnType("int")
                        .HasColumnName("panTrans");

                    b.Property<int?>("PanVol")
                        .HasColumnType("int")
                        .HasColumnName("panVol");

                    b.Property<int?>("PanVol5CntNeg")
                        .HasColumnType("int")
                        .HasColumnName("panVol5CntNeg");

                    b.Property<int?>("PanVol5CntPos")
                        .HasColumnType("int")
                        .HasColumnName("panVol5CntPos");

                    b.Property<int?>("PanVol5QuanNeg")
                        .HasColumnType("int")
                        .HasColumnName("panVol5QuanNeg");

                    b.Property<int?>("PanVol5QuanPos")
                        .HasColumnType("int")
                        .HasColumnName("panVol5QuanPos");

                    b.Property<decimal?>("PanVolTransRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("panVolTransRate");

                    b.Property<decimal?>("PrePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prePrice");

                    b.Property<DateTime?>("PreTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("preTime");

                    b.Property<int?>("PreVol")
                        .HasColumnType("int")
                        .HasColumnName("preVol");

                    b.Property<int?>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<string>("RecommandBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("recommandBy");

                    b.Property<decimal?>("RecommandPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("recommandPrice");

                    b.Property<string>("StockID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StockID");

                    b.Property<string>("StockName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StockName");

                    b.Property<int?>("StockPriority")
                        .HasColumnType("int")
                        .HasColumnName("stockPriority");

                    b.HasKey("Log_ID");

                    b.HasIndex("StockID", "Created")
                        .IsUnique();

                    b.ToTable("alertlog");
                });

            modelBuilder.Entity("SST.StockImport.Core.Entities.BuyIn", b =>
                {
                    b.Property<int>("BuyInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BuyIn_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BuyInId"));

                    b.Property<decimal>("Avg5VolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avg5VolRate");

                    b.Property<decimal>("AvgAmt10D")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmt10D");

                    b.Property<decimal>("AvgAmt20D")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmt20D");

                    b.Property<decimal>("AvgAmt5D")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmt5D");

                    b.Property<decimal>("AvgAmtSeason")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmtSeason");

                    b.Property<int>("AvgVol5D")
                        .HasColumnType("int")
                        .HasColumnName("avgVol5D");

                    b.Property<decimal?>("BuyInCount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("BuyInCount");

                    b.Property<decimal?>("BuyInPoint")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("BuyInPoint");

                    b.Property<string>("BuyInReason")
                        .HasColumnType("text")
                        .HasColumnName("BuyInReason");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("Created"));

                    b.Property<int?>("DailyNoDataCnt")
                        .HasColumnType("int")
                        .HasColumnName("dailyNoDataCnt");

                    b.Property<int>("DailyNoPriceCnt")
                        .HasColumnType("int")
                        .HasColumnName("dailyNoPriceCnt");

                    b.Property<int>("DailyNoVolCnt")
                        .HasColumnType("int")
                        .HasColumnName("dailyNoVolCnt");

                    b.Property<DateTime>("DataDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataDate");

                    b.Property<int>("If20Hight")
                        .HasColumnType("int")
                        .HasColumnName("if20Hight");

                    b.Property<int>("InstantFall")
                        .HasColumnType("int")
                        .HasColumnName("instantFall");

                    b.Property<decimal>("InstantIdx")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("instantIdx");

                    b.Property<int>("InstantMass")
                        .HasColumnType("int")
                        .HasColumnName("instantMass");

                    b.Property<int>("InstantRise")
                        .HasColumnType("int")
                        .HasColumnName("instantRise");

                    b.Property<int>("InvPredict")
                        .HasColumnType("int")
                        .HasColumnName("invPredict");

                    b.Property<DateTime?>("LastDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastDate");

                    b.Property<decimal>("LastPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("lastPrice");

                    b.Property<int>("LastVol")
                        .HasColumnType("int")
                        .HasColumnName("lastVol");

                    b.Property<decimal>("LastVolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("lastVolRate");

                    b.Property<int>("MessFall")
                        .HasColumnType("int")
                        .HasColumnName("messFall");

                    b.Property<int>("MessRise")
                        .HasColumnType("int")
                        .HasColumnName("messRise");

                    b.Property<int>("MomentAVDVol")
                        .HasColumnType("int")
                        .HasColumnName("momentAVDVol");

                    b.Property<int>("MyPredict")
                        .HasColumnType("int")
                        .HasColumnName("myPredict");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Note");

                    b.Property<decimal>("OnTimePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("onTimePrice");

                    b.Property<int>("OnTimeVol")
                        .HasColumnType("int")
                        .HasColumnName("onTimeVol");

                    b.Property<decimal>("OpenPriec")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("OpenPriec");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("playerID");

                    b.Property<string>("RecommandBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("recommandBy");

                    b.Property<string>("StockID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StockID");

                    b.Property<int>("StockLeftCount")
                        .HasColumnType("int")
                        .HasColumnName("stockLeftCount");

                    b.Property<string>("StockName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StockName");

                    b.Property<string>("StockType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("StockType");

                    b.Property<decimal?>("StopLoss")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("StopLoss");

                    b.Property<decimal?>("StopProfit")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("StopProfit");

                    b.Property<int>("TransVol")
                        .HasColumnType("int")
                        .HasColumnName("transVol");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("Updated"));

                    b.HasKey("BuyInId");

                    b.ToTable("buyin");
                });

            modelBuilder.Entity("SST.StockImport.Core.Entities.InvestBase", b =>
                {
                    b.Property<string>("StockID")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StockID");

                    b.Property<decimal?>("Avg5VolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avg5VolRate");

                    b.Property<decimal?>("AvgAmt10D")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmt10D");

                    b.Property<decimal?>("AvgAmt20D")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmt20D");

                    b.Property<decimal?>("AvgAmt5D")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmt5D");

                    b.Property<decimal?>("AvgAmtSeason")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmtSeason");

                    b.Property<int?>("AvgVol5D")
                        .HasColumnType("int")
                        .HasColumnName("avgVol5D");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("CREATED");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime?>("Created"));

                    b.Property<decimal?>("CurrPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("currPrice");

                    b.Property<int?>("DailyNoDataCnt")
                        .HasColumnType("int")
                        .HasColumnName("dailyNoDataCnt");

                    b.Property<int?>("DailyNoPriceCnt")
                        .HasColumnType("int")
                        .HasColumnName("dailyNoPriceCnt");

                    b.Property<int?>("DailyNoVolCnt")
                        .HasColumnType("int")
                        .HasColumnName("dailyNoVolCnt");

                    b.Property<decimal?>("Hprice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Hprice");

                    b.Property<string>("InstRiseFallRate")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("InstRiseFallRate");

                    b.Property<int?>("InstantBuyVol")
                        .HasColumnType("int")
                        .HasColumnName("instantBuyVol");

                    b.Property<int?>("InstantFall")
                        .HasColumnType("int")
                        .HasColumnName("instantFall");

                    b.Property<string>("InstantIdx")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("instantIdx");

                    b.Property<int?>("InstantJumpKong")
                        .HasColumnType("int")
                        .HasColumnName("instantJumpKong");

                    b.Property<int?>("InstantMass")
                        .HasColumnType("int")
                        .HasColumnName("instantMass");

                    b.Property<int?>("InstantRise")
                        .HasColumnType("int")
                        .HasColumnName("instantRise");

                    b.Property<int?>("InstantSellVol")
                        .HasColumnType("int")
                        .HasColumnName("instantSellVol");

                    b.Property<int?>("InvPredict")
                        .HasColumnType("int")
                        .HasColumnName("invPredict");

                    b.Property<DateTime?>("LastDate")
                        .HasColumnType("date")
                        .HasColumnName("lastDate");

                    b.Property<decimal?>("LastPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("lastPrice");

                    b.Property<int?>("LastVol")
                        .HasColumnType("int")
                        .HasColumnName("lastVol");

                    b.Property<decimal?>("LastVolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("lastVolRate");

                    b.Property<decimal?>("Lprice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Lprice");

                    b.Property<int?>("MessFall")
                        .HasColumnType("int")
                        .HasColumnName("messFall");

                    b.Property<int?>("MessRise")
                        .HasColumnType("int")
                        .HasColumnName("messRise");

                    b.Property<int?>("MomentAVDVol")
                        .HasColumnType("int")
                        .HasColumnName("momentAVDVol");

                    b.Property<int?>("MyPredict")
                        .HasColumnType("int")
                        .HasColumnName("myPredict");

                    b.Property<decimal?>("OnTimePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("onTimePrice");

                    b.Property<int?>("OnTimeVol")
                        .HasColumnType("int")
                        .HasColumnName("onTimeVol");

                    b.Property<decimal?>("OpenPriec")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("OpenPriec");

                    b.Property<int?>("PanVol10Cnt")
                        .HasColumnType("int")
                        .HasColumnName("panVol10Cnt");

                    b.Property<int?>("PanVol5Cnt")
                        .HasColumnType("int")
                        .HasColumnName("panVol5Cnt");

                    b.Property<int?>("PanVol5CntNeg")
                        .HasColumnType("int")
                        .HasColumnName("panVol5CntNeg");

                    b.Property<int?>("PanVol5CntPos")
                        .HasColumnType("int")
                        .HasColumnName("panVol5CntPos");

                    b.Property<string>("PanVol5Dict")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("panVol5Dict");

                    b.Property<int?>("PanVol5QuanNeg")
                        .HasColumnType("int")
                        .HasColumnName("panVol5QuanNeg");

                    b.Property<int?>("PanVol5QuanPos")
                        .HasColumnType("int")
                        .HasColumnName("panVol5QuanPos");

                    b.Property<decimal?>("PriceDiffRate0921")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("priceDiffRate0921");

                    b.Property<int?>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("Priority");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("RecDate")
                        .HasColumnType("date")
                        .HasColumnName("recDate");

                    b.Property<string>("StockName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("stockName");

                    b.Property<string>("StockType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("StockType");

                    b.Property<decimal?>("Stoploss")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("stoploss");

                    b.Property<int?>("TransVol")
                        .HasColumnType("int")
                        .HasColumnName("transVol");

                    b.Property<DateTime?>("Updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("Updated"));

                    b.Property<int?>("Vol0921")
                        .HasColumnType("int")
                        .HasColumnName("vol0921");

                    b.HasKey("StockID");

                    b.ToTable("investbase");
                });

            modelBuilder.Entity("SST.StockImport.Core.Entities.RecommandStock", b =>
                {
                    b.Property<int>("RecommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecommandID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecommandId"));

                    b.Property<decimal>("Avg5VolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avg5VolRate");

                    b.Property<decimal>("AvgAmt10D")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmt10D");

                    b.Property<decimal>("AvgAmt20D")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmt20D");

                    b.Property<decimal>("AvgAmt5D")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmt5D");

                    b.Property<decimal>("AvgAmtSeason")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmtSeason");

                    b.Property<int>("AvgVol5D")
                        .HasColumnType("int")
                        .HasColumnName("avgVol5D");

                    b.Property<string>("ByWho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ByWho");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATED");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("Created"));

                    b.Property<decimal>("CurrPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("currPrice");

                    b.Property<int>("DailyNoDataCnt")
                        .HasColumnType("int")
                        .HasColumnName("dailyNoDataCnt");

                    b.Property<int>("DailyNoPriceCnt")
                        .HasColumnType("int")
                        .HasColumnName("dailyNoPriceCnt");

                    b.Property<int>("DailyNoVolCnt")
                        .HasColumnType("int")
                        .HasColumnName("dailyNoVolCnt");

                    b.Property<int>("If20Hight")
                        .HasColumnType("int")
                        .HasColumnName("if20Hight");

                    b.Property<int>("IfDeleted")
                        .HasColumnType("int")
                        .HasColumnName("ifDeleted");

                    b.Property<int>("InstantFall")
                        .HasColumnType("int")
                        .HasColumnName("instantFall");

                    b.Property<decimal>("InstantIdx")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("instantIdx");

                    b.Property<int>("InstantMass")
                        .HasColumnType("int")
                        .HasColumnName("instantMass");

                    b.Property<int>("InstantRise")
                        .HasColumnType("int")
                        .HasColumnName("instantRise");

                    b.Property<int>("InvPredict")
                        .HasColumnType("int")
                        .HasColumnName("invPredict");

                    b.Property<DateTime?>("LastDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastDate");

                    b.Property<decimal>("LastPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("lastPrice");

                    b.Property<int>("LastVol")
                        .HasColumnType("int")
                        .HasColumnName("lastVol");

                    b.Property<decimal>("LastVolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("lastVolRate");

                    b.Property<int>("MessFall")
                        .HasColumnType("int")
                        .HasColumnName("messFall");

                    b.Property<int>("MessRise")
                        .HasColumnType("int")
                        .HasColumnName("messRise");

                    b.Property<int>("MomentAVDVol")
                        .HasColumnType("int")
                        .HasColumnName("momentAVDVol");

                    b.Property<DateTime?>("MostUpdatedNotice")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("mostUpdatedNotice");

                    b.Property<int>("MyPredict")
                        .HasColumnType("int")
                        .HasColumnName("myPredict");

                    b.Property<decimal>("OnTimePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("onTimePrice");

                    b.Property<int>("OnTimeVol")
                        .HasColumnType("int")
                        .HasColumnName("onTimeVol");

                    b.Property<decimal>("OpenPriec")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("OpenPriec");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("Priority");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("ReccDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reccDate");

                    b.Property<decimal>("RecommandPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("recommandPrice");

                    b.Property<string>("RemoveDate")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("removeDate");

                    b.Property<string>("StockID")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StockID");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("stockName");

                    b.Property<string>("StockType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("StockType");

                    b.Property<decimal>("Stoploss")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("stoploss");

                    b.Property<int>("TransVol")
                        .HasColumnType("int")
                        .HasColumnName("transVol");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("Updated"));

                    b.HasKey("RecommandId");

                    b.ToTable("recommandstock");
                });

            modelBuilder.Entity("SST.StockImport.Core.Entities.Stock60Days", b =>
                {
                    b.Property<string>("StockID")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StockID");

                    b.Property<DateTime>("StockDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("StockDate");

                    b.Property<decimal>("AccAvg5VolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("accAvg5VolRate");

                    b.Property<decimal>("AccBoolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("accBoolRate");

                    b.Property<decimal>("AccLastVolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("accLastVolRate");

                    b.Property<sbyte>("AccOpenRate")
                        .HasColumnType("tinyint")
                        .HasColumnName("accOpenRate");

                    b.Property<decimal>("BoolDown")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("boolDown");

                    b.Property<decimal>("BoolMid")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("boolMid");

                    b.Property<decimal>("BoolUp")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("boolUp");

                    b.Property<decimal>("BoolkaikouDiffRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("boolkaikouDiffRate");

                    b.Property<int>("ContLittleBlack")
                        .HasColumnType("int")
                        .HasColumnName("contLittleBlack");

                    b.Property<sbyte>("ContLittleRed")
                        .HasColumnType("tinyint")
                        .HasColumnName("contLittleRed");

                    b.Property<int?>("ContLittleSoldier")
                        .HasColumnType("int")
                        .HasColumnName("contLittleSoldier");

                    b.Property<decimal>("Droprate")
                        .HasPrecision(10, 1)
                        .HasColumnType("decimal(10,1)")
                        .HasColumnName("droprate");

                    b.Property<decimal?>("EndPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("EndPrice");

                    b.Property<decimal>("Fluctuation")
                        .HasPrecision(10, 1)
                        .HasColumnType("decimal(10,1)")
                        .HasColumnName("fluctuation");

                    b.Property<decimal?>("HPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("HPrice");

                    b.Property<DateTime?>("IntervalDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("intervalDate");

                    b.Property<decimal>("IntervalMaxPrice")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("intervalMaxPrice");

                    b.Property<int>("IntervalMaxVol")
                        .HasColumnType("int")
                        .HasColumnName("intervalMaxVol");

                    b.Property<double>("JumpKong")
                        .HasColumnType("double")
                        .HasColumnName("jumpKong");

                    b.Property<decimal>("KD_D")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("KD_D");

                    b.Property<decimal>("KD_K")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("KD_K");

                    b.Property<decimal>("KD_RSV")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("KD_RSV");

                    b.Property<decimal?>("LPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("LPrice");

                    b.Property<DateTime?>("LastDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastDate");

                    b.Property<decimal?>("MA10")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MA10");

                    b.Property<decimal?>("MA14")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MA14");

                    b.Property<decimal>("MA20")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MA20");

                    b.Property<decimal?>("MA35")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MA35");

                    b.Property<decimal?>("MA5")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MA5");

                    b.Property<decimal?>("MA60")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MA60");

                    b.Property<int?>("MV10")
                        .HasColumnType("int")
                        .HasColumnName("MV10");

                    b.Property<int?>("MV14")
                        .HasColumnType("int")
                        .HasColumnName("MV14");

                    b.Property<int>("MV20")
                        .HasColumnType("int")
                        .HasColumnName("MV20");

                    b.Property<int?>("MV35")
                        .HasColumnType("int")
                        .HasColumnName("MV35");

                    b.Property<int?>("MV5")
                        .HasColumnType("int")
                        .HasColumnName("MV5");

                    b.Property<int?>("MV60")
                        .HasColumnType("int")
                        .HasColumnName("MV60");

                    b.Property<decimal>("MaxPrice3M")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("MaxPrice3M");

                    b.Property<int>("MaxVol3M")
                        .HasColumnType("int")
                        .HasColumnName("MaxVol3M");

                    b.Property<int>("MiddleVol")
                        .HasColumnType("int")
                        .HasColumnName("middleVol");

                    b.Property<decimal?>("OpenPriec")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("OpenPriec");

                    b.Property<int>("Pan3Distance")
                        .HasColumnType("int")
                        .HasColumnName("Pan3Distance");

                    b.Property<string>("Pan3Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Pan3Status");

                    b.Property<sbyte>("PanVol50CntNeg")
                        .HasColumnType("tinyint")
                        .HasColumnName("panVol50CntNeg");

                    b.Property<sbyte>("PanVol50CntPos")
                        .HasColumnType("tinyint")
                        .HasColumnName("panVol50CntPos");

                    b.Property<int>("PanVol5CntNeg")
                        .HasColumnType("int")
                        .HasColumnName("panVol5CntNeg");

                    b.Property<int>("PanVol5CntPos")
                        .HasColumnType("int")
                        .HasColumnName("panVol5CntPos");

                    b.Property<int>("PanVol5QuanNeg")
                        .HasColumnType("int")
                        .HasColumnName("panVol5QuanNeg");

                    b.Property<int>("PanVol5QuanPos")
                        .HasColumnType("int")
                        .HasColumnName("panVol5QuanPos");

                    b.Property<int>("PanvolScore")
                        .HasColumnType("int")
                        .HasColumnName("panvolScore");

                    b.Property<decimal>("SerialLow")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("serialLow");

                    b.Property<decimal>("Stable")
                        .HasPrecision(10, 1)
                        .HasColumnType("decimal(10,1)")
                        .HasColumnName("stable");

                    b.Property<int>("Stable3M")
                        .HasColumnType("int")
                        .HasColumnName("stable3M");

                    b.Property<int>("TurnoverDiff")
                        .HasColumnType("int")
                        .HasColumnName("turnoverDiff");

                    b.Property<decimal>("TurnoverRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("turnoverRate");

                    b.Property<long?>("Vol")
                        .HasColumnType("bigint")
                        .HasColumnName("Vol");

                    b.HasKey("StockID", "StockDate");

                    b.ToTable("stock60days");
                });

            modelBuilder.Entity("SST.StockImport.Core.Entities.TradeData", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trade_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TradeId"));

                    b.Property<decimal>("AccAvg5VolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("accAvg5VolRate");

                    b.Property<decimal>("AccBoolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("accBoolRate");

                    b.Property<decimal>("AccLastVolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("accLastVolRate");

                    b.Property<int>("ActiveKong3D")
                        .HasColumnType("int")
                        .HasColumnName("activeKong3D");

                    b.Property<decimal>("Avg5VolPerTrans")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avg5VolPerTrans");

                    b.Property<decimal>("Avg5VolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avg5VolRate");

                    b.Property<decimal>("AvgAmt5D")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avgAmt5D");

                    b.Property<int>("AvgPanVol")
                        .HasColumnType("int")
                        .HasColumnName("avgPanVol");

                    b.Property<int>("AvgVol5D")
                        .HasColumnType("int")
                        .HasColumnName("avgVol5D");

                    b.Property<int>("BigVol")
                        .HasColumnType("int")
                        .HasColumnName("bigVol");

                    b.Property<string>("BoolDirection")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("boolDirection");

                    b.Property<decimal?>("BoolDownDeviation")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("boolDownDeviation");

                    b.Property<decimal?>("BoolKaikou")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("boolKaikou");

                    b.Property<int>("BoolKaikouCnt")
                        .HasColumnType("int")
                        .HasColumnName("boolKaikouCnt");

                    b.Property<decimal?>("BoolMidDeviation")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("boolMidDeviation");

                    b.Property<decimal?>("BoolUpDeviation")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("boolUpDeviation");

                    b.Property<string>("BoolinPosition")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("boolinPosition");

                    b.Property<decimal>("BoxBottom")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("boxBottom");

                    b.Property<decimal>("BoxTop")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("boxTop");

                    b.Property<string>("DIF")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("DIF");

                    b.Property<int>("DeffectiveKong")
                        .HasColumnType("int")
                        .HasColumnName("deffectiveKong");

                    b.Property<decimal>("DownShadow")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("downShadow");

                    b.Property<int>("EPS")
                        .HasColumnType("int")
                        .HasColumnName("EPS");

                    b.Property<int>("EndShadow5")
                        .HasColumnType("int")
                        .HasColumnName("EndShadow5");

                    b.Property<int?>("FarenSerialAmt")
                        .HasColumnType("int")
                        .HasColumnName("farenSerialAmt");

                    b.Property<int?>("FarenSerialDays")
                        .HasColumnType("int")
                        .HasColumnName("farenSerialDays");

                    b.Property<int>("FinancialReport")
                        .HasColumnType("int")
                        .HasColumnName("financialReport");

                    b.Property<int?>("ForeigneAmt")
                        .HasColumnType("int")
                        .HasColumnName("foreigneAmt");

                    b.Property<int?>("ForeigneSerealDays")
                        .HasColumnType("int")
                        .HasColumnName("foreigneSerealDays");

                    b.Property<string>("ForgneSwitch")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("forgneSwitch");

                    b.Property<decimal?>("FrstOntimePredict")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("frstOntimePredict");

                    b.Property<sbyte>("FrstOntimeTrain")
                        .HasColumnType("tinyint")
                        .HasColumnName("frstOntimeTrain");

                    b.Property<sbyte>("FrstPredict2d")
                        .HasColumnType("tinyint")
                        .HasColumnName("frstPredict2d");

                    b.Property<sbyte>("FrstTrainPredt2d")
                        .HasColumnType("tinyint")
                        .HasColumnName("frstTrainPredt2d");

                    b.Property<int>("GrossProfit")
                        .HasColumnType("int")
                        .HasColumnName("grossProfit");

                    b.Property<decimal?>("HPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("HPrice");

                    b.Property<int>("InstantFall")
                        .HasColumnType("int")
                        .HasColumnName("instantFall");

                    b.Property<int>("InstantMass")
                        .HasColumnType("int")
                        .HasColumnName("instantMass");

                    b.Property<int>("InstantRise")
                        .HasColumnType("int")
                        .HasColumnName("instantRise");

                    b.Property<int?>("InvestAmt")
                        .HasColumnType("int")
                        .HasColumnName("InvestAmt");

                    b.Property<int?>("InvestSerealDays")
                        .HasColumnType("int")
                        .HasColumnName("InvestSerealDays");

                    b.Property<string>("InvwstSwitch")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("invwstSwitch");

                    b.Property<decimal>("JumpKong")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("jumpKong");

                    b.Property<decimal>("KD_D")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("KD_D");

                    b.Property<decimal>("KD_K")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("KD_K");

                    b.Property<decimal>("KD_RSV")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("KD_RSV");

                    b.Property<decimal>("KShadow")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("kShadow");

                    b.Property<decimal?>("LPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("LPrice");

                    b.Property<DateTime?>("LastDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastDate");

                    b.Property<decimal>("LastPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("lastPrice");

                    b.Property<int>("LastRongquanDiff")
                        .HasColumnType("int")
                        .HasColumnName("lastRongquanDiff");

                    b.Property<int>("LastRongziDiff")
                        .HasColumnType("int")
                        .HasColumnName("lastRongziDiff");

                    b.Property<int>("LastVol")
                        .HasColumnType("int")
                        .HasColumnName("lastVol");

                    b.Property<decimal>("LastVolRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("lastVolRate");

                    b.Property<string>("LegalPersonNote")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("LegalPersonNote");

                    b.Property<string>("LongtermNote")
                        .HasColumnType("text")
                        .HasColumnName("longtermNote");

                    b.Property<decimal>("LowHigh5")
                        .HasPrecision(10, 1)
                        .HasColumnType("decimal(10,1)")
                        .HasColumnName("LowHigh5");

                    b.Property<decimal>("LowShadow5")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("LowShadow5");

                    b.Property<int>("Lowavg5")
                        .HasColumnType("int")
                        .HasColumnName("lowavg5");

                    b.Property<string>("MA10")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MA10");

                    b.Property<string>("MA20")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MA20");

                    b.Property<string>("MA5")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MA5");

                    b.Property<string>("MACD")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MACD");

                    b.Property<string>("MACDNote")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MACDNote");

                    b.Property<string>("MADirection")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MADirection");

                    b.Property<string>("MAHalfYear")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAHalfYear");

                    b.Property<string>("MANote")
                        .HasColumnType("text")
                        .HasColumnName("MANote");

                    b.Property<string>("MASeason")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MASeason");

                    b.Property<string>("MAYear")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAYear");

                    b.Property<string>("MVData")
                        .HasColumnType("text")
                        .HasColumnName("MVData");

                    b.Property<string>("MVDirection")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MVDirection");

                    b.Property<string>("MVNote")
                        .HasColumnType("text")
                        .HasColumnName("MVNote");

                    b.Property<int>("MessFall")
                        .HasColumnType("int")
                        .HasColumnName("messFall");

                    b.Property<int>("MessRise")
                        .HasColumnType("int")
                        .HasColumnName("messRise");

                    b.Property<DateTime?>("MessStart")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("messStart");

                    b.Property<sbyte>("NeuralOntimePredict")
                        .HasColumnType("tinyint")
                        .HasColumnName("neuralOntimePredict");

                    b.Property<sbyte>("NeuralOntimeTrain")
                        .HasColumnType("tinyint")
                        .HasColumnName("neuralOntimeTrain");

                    b.Property<int>("NoPVCDays")
                        .HasColumnType("int")
                        .HasColumnName("noPVCDays");

                    b.Property<sbyte>("NuralPredict2d")
                        .HasColumnType("tinyint")
                        .HasColumnName("nuralPredict2d");

                    b.Property<sbyte>("NuralTrain2d")
                        .HasColumnType("tinyint")
                        .HasColumnName("nuralTrain2d");

                    b.Property<string>("OSC")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("OSC");

                    b.Property<decimal>("OpenPriec")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("OpenPriec");

                    b.Property<sbyte>("PDiff")
                        .HasColumnType("tinyint")
                        .HasColumnName("pDiff");

                    b.Property<int>("PVCsumInDays")
                        .HasColumnType("int")
                        .HasColumnName("PVCsumInDays");

                    b.Property<string>("Pan3Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Pan3Status");

                    b.Property<sbyte>("PanVol50CntNeg")
                        .HasColumnType("tinyint")
                        .HasColumnName("panVol50CntNeg");

                    b.Property<sbyte>("PanVol50CntPos")
                        .HasColumnType("tinyint")
                        .HasColumnName("panVol50CntPos");

                    b.Property<int>("PanVol5CntNeg")
                        .HasColumnType("int")
                        .HasColumnName("panVol5CntNeg");

                    b.Property<int>("PanVol5CntPos")
                        .HasColumnType("int")
                        .HasColumnName("panVol5CntPos");

                    b.Property<int>("PanVol5QuanNeg")
                        .HasColumnType("int")
                        .HasColumnName("panVol5QuanNeg");

                    b.Property<int>("PanVol5QuanPos")
                        .HasColumnType("int")
                        .HasColumnName("panVol5QuanPos");

                    b.Property<int>("PanvolScore")
                        .HasColumnType("int")
                        .HasColumnName("panvolScore");

                    b.Property<int?>("PrgForcaet")
                        .HasColumnType("int")
                        .HasColumnName("PrgForcaet");

                    b.Property<decimal>("PriceDiffRate0921")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("priceDiffRate0921");

                    b.Property<string>("PriceGate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PriceGate");

                    b.Property<int>("Profitability")
                        .HasColumnType("int")
                        .HasColumnName("Profitability");

                    b.Property<decimal>("QuanziRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quanziRate");

                    b.Property<string>("RecNote")
                        .HasColumnType("text")
                        .HasColumnName("recNote");

                    b.Property<int>("RongquanDiff")
                        .HasColumnType("int")
                        .HasColumnName("rongquanDiff");

                    b.Property<string>("RongquanNote")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("rongquanNote");

                    b.Property<decimal>("RongquanRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("rongquanRate");

                    b.Property<int>("Rongzi")
                        .HasColumnType("int")
                        .HasColumnName("rongzi");

                    b.Property<int>("RongziDiff")
                        .HasColumnType("int")
                        .HasColumnName("rongziDiff");

                    b.Property<string>("RongziNote")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("rongziNote");

                    b.Property<decimal>("RongziRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("rongziRate");

                    b.Property<int>("Ronquan")
                        .HasColumnType("int")
                        .HasColumnName("ronquan");

                    b.Property<sbyte>("S60FrstPrd2d")
                        .HasColumnType("tinyint")
                        .HasColumnName("s60FrstPrd2d");

                    b.Property<sbyte>("S60FrstPrdOntime")
                        .HasColumnType("tinyint")
                        .HasColumnName("s60FrstPrdOntime");

                    b.Property<sbyte>("S60FrstTrain2d")
                        .HasColumnType("tinyint")
                        .HasColumnName("s60FrstTrain2d");

                    b.Property<sbyte>("S60FrstTrainOntime")
                        .HasColumnType("tinyint")
                        .HasColumnName("s60FrstTrainOntime");

                    b.Property<sbyte>("S60NuralPrd2d")
                        .HasColumnType("tinyint")
                        .HasColumnName("s60NuralPrd2d");

                    b.Property<sbyte>("S60NuralPrdOntime")
                        .HasColumnType("tinyint")
                        .HasColumnName("s60NuralPrdOntime");

                    b.Property<sbyte>("S60NuralTrain2d")
                        .HasColumnType("tinyint")
                        .HasColumnName("s60NuralTrain2d");

                    b.Property<sbyte>("S60NuralTrainOntime")
                        .HasColumnType("tinyint")
                        .HasColumnName("s60NuralTrainOntime");

                    b.Property<sbyte>("S60XgPrd2d")
                        .HasColumnType("tinyint")
                        .HasColumnName("s60XgPrd2d");

                    b.Property<sbyte>("S60XgPrdOntime")
                        .HasColumnType("tinyint")
                        .HasColumnName("s60XgPrdOntime");

                    b.Property<sbyte>("S60XgTrain2d")
                        .HasColumnType("tinyint")
                        .HasColumnName("s60XgTrain2d");

                    b.Property<sbyte>("S60XgTrainOntime")
                        .HasColumnType("tinyint")
                        .HasColumnName("s60XgTrainOntime");

                    b.Property<int>("SerialLowDiffRate")
                        .HasColumnType("int")
                        .HasColumnName("serialLowDiffRate");

                    b.Property<int>("SerialLowPSV")
                        .HasColumnType("int")
                        .HasColumnName("serialLowPSV");

                    b.Property<int>("SerialNoPanDiffQuant")
                        .HasColumnType("int")
                        .HasColumnName("serialNoPanDiffQuant");

                    b.Property<string>("StateStr")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("stateStr");

                    b.Property<decimal?>("StockDiff")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("StockDiff");

                    b.Property<decimal?>("StockDiffRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("StockDiffRate");

                    b.Property<string>("StockID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StockID");

                    b.Property<string>("StockName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StockName");

                    b.Property<decimal?>("StockPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("StockPrice");

                    b.Property<string>("StockType")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("StockType");

                    b.Property<int>("TipPrice")
                        .HasColumnType("int")
                        .HasColumnName("TipPrice");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("TransDate");

                    b.Property<string>("TransDirection")
                        .HasColumnType("text")
                        .HasColumnName("transDirection");

                    b.Property<int>("TransVol")
                        .HasColumnType("int")
                        .HasColumnName("transVol");

                    b.Property<int>("TurnoverDiff")
                        .HasColumnType("int")
                        .HasColumnName("turnoverDiff");

                    b.Property<decimal>("TurnoverRate")
                        .HasPrecision(10, 1)
                        .HasColumnType("decimal(10,1)")
                        .HasColumnName("turnoverRate");

                    b.Property<decimal>("UpShadow")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("upShadow");

                    b.Property<long?>("Vol")
                        .HasColumnType("bigint")
                        .HasColumnName("Vol");

                    b.Property<int>("Vol0921")
                        .HasColumnType("int")
                        .HasColumnName("vol0921");

                    b.Property<int>("VolMonthMax")
                        .HasColumnType("int")
                        .HasColumnName("volMonthMax");

                    b.Property<decimal>("WaveRate")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("waveRate");

                    b.Property<decimal>("WeekVol")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("weekVol");

                    b.Property<sbyte>("XgOntimePredict")
                        .HasColumnType("tinyint")
                        .HasColumnName("xgOntimePredict");

                    b.Property<sbyte>("XgOntimeTrain")
                        .HasColumnType("tinyint")
                        .HasColumnName("xgOntimeTrain");

                    b.Property<sbyte>("XgPredict2d")
                        .HasColumnType("tinyint")
                        .HasColumnName("xgPredict2d");

                    b.Property<sbyte>("XgTrainPredt2d")
                        .HasColumnType("tinyint")
                        .HasColumnName("xgTrainPredt2d");

                    b.HasKey("TradeId");

                    b.ToTable("tradedata");
                });
#pragma warning restore 612, 618
        }
    }
}
