// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SST.StockImport.Infrastructure.Data;

#nullable disable

namespace SST.StockImport.Infrastructure.Migrations
{
    [DbContext(typeof(StockImportDbContext))]
    [Migration("20251123053447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SST.StockImport.Core.Entities.AlertLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("alert_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("JobId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("job_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext")
                        .HasColumnName("stack_trace");

                    b.Property<string>("StockCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("stock_code");

                    b.HasKey("Id");

                    b.HasIndex("AlertType")
                        .HasDatabaseName("idx_alert_type");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_created_at");

                    b.HasIndex("JobId")
                        .HasDatabaseName("idx_job_id");

                    b.HasIndex("StockCode")
                        .HasDatabaseName("idx_stock_code");

                    b.ToTable("alertlog");
                });

            modelBuilder.Entity("SST.StockImport.Core.Entities.ImportJob", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext")
                        .HasColumnName("error_message");

                    b.Property<string>("ExecutorIdentity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("executor_identity");

                    b.Property<string>("ExecutorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("executor_type");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int")
                        .HasColumnName("failed_count");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("market");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("int")
                        .HasColumnName("success_count");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int")
                        .HasColumnName("total_count");

                    b.Property<string>("TriggerIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("trigger_ip_address");

                    b.HasKey("Id");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("idx_start_time");

                    b.HasIndex("ExecutorType", "ExecutorIdentity")
                        .HasDatabaseName("idx_executor");

                    b.HasIndex("Market", "Status")
                        .HasDatabaseName("idx_market_status");

                    b.ToTable("import_job");
                });

            modelBuilder.Entity("SST.StockImport.Core.Entities.Stock60Days", b =>
                {
                    b.Property<string>("StockCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("stock_code");

                    b.Property<decimal?>("Avg20Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avg_20_price");

                    b.Property<decimal?>("Avg5Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avg_5_price");

                    b.Property<long?>("Avg5Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("avg_5_volume");

                    b.Property<decimal?>("Avg60Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("avg_60_price");

                    b.Property<long?>("Avg60Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("avg_60_volume");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_update");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("StockCode");

                    b.HasIndex("LastUpdate")
                        .HasDatabaseName("idx_last_update");

                    b.ToTable("stock60days");
                });

            modelBuilder.Entity("SST.StockImport.Core.Entities.TradeData", b =>
                {
                    b.Property<string>("StockCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("stock_code")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("trade_date")
                        .HasColumnOrder(1);

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("close_price");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("high_price");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("low_price");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("market");

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("open_price");

                    b.Property<int?>("TradeCount")
                        .HasColumnType("int")
                        .HasColumnName("trade_count");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("StockCode", "TradeDate");

                    b.HasIndex("TradeDate")
                        .HasDatabaseName("idx_trade_date");

                    b.HasIndex("Market", "TradeDate")
                        .HasDatabaseName("idx_market_date");

                    b.ToTable("tradedata");
                });

            modelBuilder.Entity("SST.StockImport.Core.Entities.AlertLog", b =>
                {
                    b.HasOne("SST.StockImport.Core.Entities.ImportJob", "ImportJob")
                        .WithMany("AlertLogs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImportJob");
                });

            modelBuilder.Entity("SST.StockImport.Core.Entities.ImportJob", b =>
                {
                    b.Navigation("AlertLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
