// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SST.StockImport.Infrastructure.Data;

#nullable disable

namespace SST.StockImport.Infrastructure.Migrations
{
    [DbContext(typeof(StockImportDbContext))]
    partial class StockImportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SST.StockImport.Core.Entities.ScheduleExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<int>("FailCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("fail_count");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("execution_date");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("ResultMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("result_message")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<string>("ScheduleSlot")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("schedule_slot")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("success_count");

                    b.Property<string>("TaskChain")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("task_chain")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<string>("TaskName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("task_name")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExecutionDate", "ScheduleSlot" }, "UK_execution")
                        .IsUnique();

                    b.ToTable("schedule_execution", (string)null);
                });

            modelBuilder.Entity("SST.StockImport.Core.Entities.ScheduleExecutionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("json")
                        .HasColumnName("details")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("execution_date");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("operation")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<DateTime>("OperationTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("operation_time");

                    b.Property<string>("ScheduleSlot")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("schedule_slot")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.Property<string>("TaskChain")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("task_chain")
                        .HasAnnotation("MySql:CharSet", "utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionDate", "IX_schedule_execution_log_execution_date");

                    b.ToTable("schedule_execution_log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
